version: '3'
services:
  mosquitto:
    image: toke/mosquitto:latest
    ports:
      - "1883:1883"
  temperature:
    image: agnathan/virtual-sensor:latest
    links:
      - mosquitto
    environment:
      hostname: mosquitto
      name: 'temperature'
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --smallfiles --rest --auth
