version: '3'
services:
  mosquitto-tls:
    image: ssgdrdiot/mosquitto:latest
    ports:
      - "8883:8883"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --smallfiles
